# MS SQL Server version
spring:
  datasource:
    url: jdbc:sqlserver://LAPTOP-D0ANQNSC;databaseName=Rentier
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: kjaniszewski
    password: Chrisjan123


# Azure SQL version
#spring:
#  datasource:
#    url: jdbc:sqlserver://kjsql-rentier.database.windows.net:1433;database=rentier;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    username: kjaniszewski@kjsql-rentier
#    password: Chrisjan123

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        format_sql: true
  security:
    user:
      name: sa
      password: sa

#useful in the application to be able to debug
logging:
  level:
    root: info

#H2 version
#spring:
#  datasource:
#    url: jdbc:h2:mem:testDb
#    driver-class-name: org.h2.Driver
#    username:
#    password:
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    hibernate.ddl-auto: create
#    show-sql: false
#    properties:
#      hibernate:
#        format_sql: false
#  security:
#    user:
#      name: sa
#      password: sa
